### ISSUE TITLE
Part 5 of settings not showing on discord

### ISSUE THREAD

**Issue by taithethai** [WFCD/genesis#103]
Reproduction steps?
go to a text channel, (preferably one that's not actually being used) and `enable * in #CHANNEL for @ROLE`
set ping for the following:
` alerts catalyst nitain reactor sorties tellurium`
track the following:
`catalyst exilus forma nitain reactor tellurium`
type in /settings

Part 5 of settings isn't showing for me.

If I have enough time, I'll try and see if I make the changes myself, but no promises.

**Comment by aliasfalse** [comment]
could you show what exactly you're seeing for settings?

there can be a very long list and it's not necessarily 5 parts, so i need more specificty  on what you're looking for

**Comment by taithethai** [comment]
![wfsettingsbroken](https://cloud.githubusercontent.com/assets/22222650/26755181/23c1dd2e-4856-11e7-94a4-efad1ff22b87.PNG)

**Comment by taithethai** [comment]
It's like there's too much text in part 5, causing it to be rejected by Discord.

**Comment by aliasfalse** [comment]
yeah, changed the chunk size. should be fine now.
