### ISSUE TITLE
Welcome?

### ISSUE THREAD

**Issue by mariley84** [WFCD/genesis#112]
I'm trying to see if Genesis can welcome new members to my Server. Am I missing the command? ( SHE IS AMAZING BY THE WAY!!!)

**Comment by aliasfalse** [comment]
http://genesis.morningstar.ninja

already exists

**Comment by mariley84** [comment]
Ok awesome! I clicked on the link and it just tried to make me add Genesis again. I apologize if I'm missing something, but how do I make Genesis welcome folk?

**Comment by aliasfalse** [comment]
ooop, gave you the wrong link.  http://genesis.warframestat.us details the documentation. 
http://genesis.warframestat.us/#welcoming will take you where you wanna go
