### ISSUE TITLE
Feature idea: have quiet hours where track is paused

### ISSUE THREAD

**Issue by derwild** [WFCD/genesis#118]
I've enabled the tracking for alerts on a dedicated channel on my server, which is great, when I'm at home doing other stuff, because I can just hop into warframe when a good reward comes up. 
In contrast to that, when I'm at work, I don't want to have those notifications popping up on my phone all the time, because I can't do them anyways while at work. 
At the moment I solved it by muting the channel on my phone and potentially unmitigated it, when I get back home. 

It would be great, when you can configure "quiet hours" in which there are no notifications. 

The best case would be, if you can configure it on channel level, because you can then have another channel which posts news, updates baro etc and you probably don't want to mute those ;-)

**Comment by aliasfalse** [comment]
Hi. This is the reason DnD (Do not Disturb) exists on discord. I'd suggest using that.

**Comment by derwild** [comment]
That would work, when I would not want to get any messages from discord, but I still want to get those of my friends or in other channels.
Just nor from genesis, when I can't even play to get those rewards

**Comment by aliasfalse** [comment]
can't you mute those channels when you don't want messages from them?

**Comment by derwild** [comment]
Well, I can permanently mute it. When mute it in the morning when going to work, I have to unmute it manually again, when I'm back home.
I don't know of a way to mute a channel only for a certain time of the day

**Comment by aliasfalse** [comment]
so you want it, like timed? the problem is that you'd also have to set it all in UTC. tbh, it seems like a strange thing to do. what if you're working late one day and it starts dinging while you're at work and can't get home?

**Comment by derwild** [comment]
Hm, I see..
How about this: Could you set it to only post a notification, when there is at least one user in the channel online?
This way it only rings, when there is at least one person, that is likely to be interested in the notification at that moment.
Most people have their discord open, when they are at home and at the pc.
Admitted, when one of the users is on holiday and at home all day, but I would say that is rather rare and when it happens one just has to deal with it ;-)

**Comment by aliasfalse** [comment]
I'm transitioning the bot eventually to use webhooks, so that wouldn't really be possible. And it would always detect itself online (obviously it could ignore bots, but you see how it's a landslide problem).

Discord already has the functionality for muting channels, so I don't see a reason to implement this, personally.

**Comment by derwild** [comment]
Hm, ok
