### ISSUE TITLE
/set ping command not working for multi-word items

### ISSUE THREAD

**Issue by XenHat** [WFCD/genesis#119]
Example: `/set ping orokin reactor`
`/set ping ferrite` works properly, so does `/wiki Orokin Reactor`
Using quotes does not appear to help.

**Comment by ScruffyRules** [comment]
Heyo Xen, that's because orokin reactor has been shortened down to just reactor (same goes for catalyst)
This is mostly because of how commands are handle as itt would be more complex to allow multi word keys

**Comment by XenHat** [comment]
Ah, okay. Thanks!
