### ISSUE TITLE
/where Command does not work

### ISSUE THREAD

**Issue by Vashakar** [WFCD/genesis#123]
https://i.imgur.com/8H9iR1n.png

**Comment by aliasfalse** [comment]
The `/whereis` command works just fine. `/where` has always been a grammatically incorrect shortening of it.

**Comment by aliasfalse** [comment]
The `/help` command exists to clear up these questions. Please make sure to check there first, or on our documentation site: http://genesis.warframestat.us or on the discord server: https://discord.gg/DuFunUv
