### ISSUE TITLE
Weapon's Riven disposition preview is inverted

### ISSUE THREAD

**Issue by sashareds** [WFCD/genesis#129]
The icon for riven disposition displays in an inverted state I think. 
Also, in the Mac desktop app, it is blurry and with negative margins. 

![Inverted disposition](https://image.prntscr.com/image/17vYTJEERseQ4L5BgvlWcg.png "Wrong way")
![Inverted disposition](https://image.prntscr.com/image/oxgWgR27RgyCt-chcS6bCg.png "Wrong way")

When the order should be displayed like that 
![Correct disposition](https://image.prntscr.com/image/_ZPM5gHyTQetH0HkpjETCQ.png "Right way")
![Correct disposition](https://image.prntscr.com/image/rfDAK6kCRI6azeWrUV_5bQ.png "Right way")

The browser version of discord app displays icons crispy and no bluer, at least in Safari.
![Cripsy in browser](https://image.prntscr.com/image/IODP3tc7QpOFr9QXTtFxRA.png "Right way")

I presume u were using some html unicode characters for displaying icons? If so, their rendering tends to be inconsistent across browsers

**Comment by aliasfalse** [comment]
yeah, that's pretty much why i stick to what i see on windows and android, because they conform with web standards better.

![image](https://user-images.githubusercontent.com/7128721/31025157-14ac02d4-a507-11e7-8815-ae892067d4bf.png)

![image](https://user-images.githubusercontent.com/7128721/31025214-5b787b8e-a507-11e7-8d04-32c638573ac8.png)

I could theoretically do the separate emoji, the problem is running out of space on the server where they're all hosted, since we're limited to 50 total and are about out of them.

**Comment by aliasfalse** [comment]
This is where all the setup happens: https://github.com/WFCD/genesis/blob/master/src/embeds/WeaponEmbed.js

**Comment by sashareds** [comment]
Yeah I see it now. Thanks. 
And that's why you went for inverted disposition display? Cuz this type of chars are more visible on the dark app theme?
Just trying to figure out what would be better.. stick to the wiki conventions or adjust it for discord cross-app'ness

**Comment by aliasfalse** [comment]
my problem with the wiki is they'll have a convention for a few months, then just keep changing when they feel like it. I don't consider the wiki to be the "end all" for formatting advice. I'm fine either way, and it's possible i could make it work easy enough and have more servers dedicated to holding those extra emoji if it happens. it'd probably be good to have them in a config so it's more ready for people that desire to self-host.

**Comment by sashareds** [comment]
> my problem with the wiki is they'll have a convention for a few months, then just keep changing when they feel like it.

Reminds of the situation in the javascript framework field, does it not? :)

What do u think about inverted display? I still think we all used to see filled circles and an indication of disposition level, rather than empty ones

like that    
`const dispositions = ['\\⚫\\⚫\\⚫\\⚫\\⚫', '\\⚫\\⚫\\⚫\\⚫\\⚪', '\\⚫\\⚫\\⚫'\\⚪\\⚪, '\\⚫\\⚫\\⚪\\⚪\\⚪', '\\⚫\\⚪\\⚪\\⚪\\⚪', '\\⚪\\⚪\\⚪\\⚪\\⚪'];`

**Comment by sashareds** [comment]
Speaking of web standards. Safari shows them well.. it's just Discord app.. not sure what html engine they use. But seems defo no webkit

**Comment by aliasfalse** [comment]
i can swap them, if you think that's enough
