### ISSUE TITLE
l10n support

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/genesis#140]
### Genesis Issue
---
---

**Summary (short):** Add support for alternate provided languages

---
**Description:**
~~String manager~~
- [x] Add i18n tagged template literal
- [x] Able to send broadcasts
- [x] Passive so it can be added slowly.

Commands:
- [x] Alerts
- [ ] Baro
- [ ] ConclaveChallenges
- [ ] Construction
- [ ] Darvo
- [ ] EarthCycle
- [ ] Enemies
- [ ] Event
- [ ] FeaturedDeals
- [ ] Fissures
- [x] Invasions
- [ ] News
- [ ] PopularSale
- [ ] PrimeAccess
- [ ] Simaris
- [ ] Sorties
- [ ] Syndicates
- [ ] Updates
- [ ] DeleteBuild
- [ ] ListBuilds
- [ ] SetField
- [ ] Bug
- [ ] Help
- [ ] Info
- [ ] Invite
- [ ] Ping
- [ ] Support
- [ ] AddCustomCommand
- [ ] DeleteCustomCommand
- [ ] Avatar
- [ ] DeleteWebhook
- [ ] LeaveServer
- [ ] Reload
- [ ] Servers
- [ ] AddRole
- [ ] JoinRole
- [ ] LeaveRole
- [ ] RemoveRole
- [ ] RoleIds
- [ ] Roles
- [ ] Create
- [ ] RoomCreation

(not doing settings commands for the time being, most of them are sensitive because they correspond to actual database values)

- [ ] Hug
- [ ] Joke
- [ ] ServerInfo
- [ ] PollInline
- [ ] UserInfo
- [ ] Arcane
- [ ] Armor
- [ ] BuildChart
- [ ] Damage
- [ ] Efficiency
- [ ] FrameStats
- [ ] Mod
- [ ] PriceCheck (might be more complicated, since it drives off of an outside service
- [ ] Profile
- [ ] Progression
- [ ] Raid
- [ ] Shields
- [ ] Tutorial
- [ ] Weapon
- [ ] Whatsin
- [ ] Whereis
- [ ] Wiki

System Locations
- [ ] NotifySettingsChange (message Manager)

Embeds:
- [x] AlertEmbed
- [ ] BuildEmbed
- [ ] ConclaveChallengeEmbed
- [ ] ConstructionEmbed
- [ ] DarvoEmbed
- [ ] EarthCycleEmbed
- [ ] EnableInfoEmbed
- [ ] EnableUsageEmbed
- [ ] EventEmbed
- [ ] FissureEmbed
- [ ] FrameEmbed
- [x] InvasionEmbed
- [ ] NewsEmbed
- [ ] PriceCheckEmbed
- [ ] ProfileEmbed
- [ ] RaidEmbed
- [ ] RolesEmbed
- [ ] SalesEmbed
- [ ] ServerInfoEmbed
- [ ] SettingsEmbed
- [ ] ShieldEmbed
- [ ] SimarisEmbed
- [ ] SortieEmbed
- [ ] SyndicateEmbed
- [ ] UserInfoEmbed
- [ ] VoidTraderEmbed
- [ ] WeaponEmbed
- [ ] WhatsinEmbed
- [ ] WhereisEmbed
- [ ] WikiEmbed

---
**If issue, Reproduction:**

---
**Mockups, screenshots, evidence:**

---

(Check one)
- [ ] Issue
- [x] Suggestion

**Comment by mephasor** [comment]
I'd like to help. 
Do you guy have a specific idea how this is supposed to be done? 
I see strings.json, but there are just a couple. 
Alert texts etc. could be done in the languages as well, since the data is already there, or am I wrong?

**Comment by aliasfalse** [comment]
The help needed is implementing it so that the strings can be translated. strings.json isn't of much use at the moment because the previous system i was attempting to use was tedious and not easily managed because of the scale it could reach for replaceable elements.

I have the architecture done mentally, I'm trying to have time to sit down and implement the beginning.

**Comment by aliasfalse** [comment]
And yes, alert texts will be able to be eventually, but not at present because the data project needs those completed and implemented into the parser first.

**Comment by aliasfalse** [comment]
@mephasor right now, if you're willing to help, most of what i need help with is moving the strings into the en.json for english so they can all be gathered and translated.

**Comment by mephasor** [comment]
Allrighty. Will get on that tonight.

**Comment by TobiTenno** [comment]
@mephasor i finally have the actual structure done, in the feature/l10n branch

**Comment by mephasor** [comment]
Awesome. Looks great, I will start go through the other files after work

**Comment by TobiTenno** [comment]
Cool. I just added all the details, and if you're able to blast through a ton, that would be _amaaaaaazing_

**Comment by TobiTenno** [comment]
@mephasor still able to help?

**Comment by mephasor** [comment]
yes, definitely.
Just had to get married. Back to normal routine starting next week!

**Comment by TobiTenno** [comment]
lol, marriage def comes first. looking forward to getting together with you on this!

**Comment by LwkasCrystian** [comment]
Could I help with the Portuguese translation? I tried to translate manually, but I gave up ... or rather, I could not

**Comment by TobiTenno** [comment]
sure, hop on our discord (https://discord.gg/DuFunUv) and send a DM to DJNeonNight. This branch is specifically with implementing the architecture, we have actual translations in a separate branch.

**Comment by TobiTenno** [comment]
for those of you watching this, i've finally got a passive framework in place that is readily available per-command and each embed when passed into it. I'd like help implementing it, but it's finally at a point where i can add it slowly without hindering existing development.

@mephasor if you're still interested, the pattern is much simpler and easier to pick up on, no manual replaces, just adding the template tag and adding the strings as needed to the locale json.
