### ISSUE TITLE
/set ping not producing a response

### ISSUE THREAD

**Issue by mephasor** [WFCD/genesis#142]
### Genesis Issue
---
---

**Summary (short):**
/set ping command not producing an output

---
**Description:**
According to http://genesis.warframestat.us/#tracking, /set ping is supposed to list all pingable items. In my case it does not respond to the command at all. 

---
**If issue, Reproduction:**
Call `/set ping` in a non-dm

---
**Mockups, screenshots, evidence:** ![image](https://user-images.githubusercontent.com/3739250/32379323-fb8f8d70-c08b-11e7-9b65-4902fbb1cfa4.png)

---

(Check one)
- [x] Issue
- [ ] Suggestion

**Comment by aliasfalse** [comment]
@mephasor i'm gonna need a screenshot.

**Comment by mephasor** [comment]
Sure, 
![image](https://user-images.githubusercontent.com/3739250/32379323-fb8f8d70-c08b-11e7-9b65-4902fbb1cfa4.png)

**Comment by aliasfalse** [comment]
do you have perms to do so on the guild?

**Comment by mephasor** [comment]
It's my server. Here a screenshot of me setting a ping for alerts.
I did remove some rights from the bot (the machines are taking over!). Which one is requred for /set ping? it is allowed to message

![image](https://user-images.githubusercontent.com/3739250/32379546-8c674874-c08c-11e7-95e6-432128763c0f.png)

**Comment by aliasfalse** [comment]
it shouldn't need any besides embeds. there is a message on our faq to not mess with the perms after they're set with the auth link, so that's kind of on you to manage them now, but i'm looking into set ping not returning anything on its own.

**Comment by aliasfalse** [comment]
Just about done on the fix, @mephasor, just waiting for automated stuff

**Comment by aliasfalse** [comment]
once it's built, please verify and i'll close this out, @mephasor

**Comment by aliasfalse** [comment]
closing, because the fix is out. please comment with further issues.
