### ISSUE TITLE
Plains Night Preperation.

### ISSUE THREAD

**Issue by NaleshSA** [WFCD/genesis#151]
### Genesis Issue
---
---

**Summary (short):** A ping notification to warn people that night in the plains is coming soon.

---
**Description:** A Cetus style ping notification that goes off 10-15 min before night time, possibly with granularity( /set ping CetusNight 15 @Eidolon for example )

---
**If issue, Reproduction:**

---
**Mockups, screenshots, evidence:**

---

(Check one)
- [ ] Issue
- [x] Suggestion

**Comment by TobiTenno** [comment]
the format would probably end up as `/set ping cetus.night.15 @Eidolon`, to fit with how we've done other sub-divisions

**Comment by TobiTenno** [comment]
Hey, @NaleshSA sorry I haven't gotten around to this yet. I'm looking at doing it this weekend or soon after. No promises, cause we all get busy, ya know?

**Comment by TobiTenno** [comment]
separated cetus.night and cetus.day done.... what level of granularity would you want? I've still never gotten an answer from many people

**Comment by TobiTenno** [comment]
@NaleshSA live in the bot now. Enjoy. The tracking syntax is `/track cetus.day.10` for 10 minutes remaining in day, and `/track cetus.night.10` for 10 minutes remaining in night. You can set whichever values you want.
