### ISSUE TITLE
Can't untrack all fissure types

### ISSUE THREAD

**Issue by JoK3R-GER** [WFCD/genesis#153]
### Genesis Issue
---
---

**Summary (short):**
You can't untrack all fissure types.
---
**Description:**
There are fissure types which can be added with the _/track all_ command, but can't be untracked by _/untrack all_ or by their specific type. You can see the affected types in the screenshot below.

---
**If issue, Reproduction:**
1. /track all
2. /untrack all
3. See the affected fissure types.
---
**Mockups, screenshots, evidence:**
![genesis_untrack_fissures_bug](https://user-images.githubusercontent.com/9644149/34062612-c8931e54-e1ed-11e7-9943-b3aaa1e21de2.PNG)

---

(Check one)
- [x] Issue
- [ ] Suggestion

**Comment by TobiTenno** [comment]
ah shoot, i know what happened

**Comment by TobiTenno** [comment]
@JoK3R-GER they should be removed now. could you try adding them and removing them again?

**Comment by JoK3R-GER** [comment]
It's working now. Thank you.

**Comment by TobiTenno** [comment]
Awesome. Sadly I had to delete 100k+ db lines to make it work, but all in the service of fixing that db, lol.
