### ISSUE TITLE
Reset command to set server back to base settings

### ISSUE THREAD

**Issue by AcesGamingUK** [WFCD/genesis#156]
### Genesis Issue
---
---

**Summary (short):**

---
**Description:**
add a default option for the bot.
`/reset = set the bot back to default settings`
so it basically resets as if it was first added to a server?
if it too much to do then it's no big deal, just thought it would be useful for "debugging" as you could ask `"have you tried resetting the bot to see if that fixes your issue?"`

---
**If issue, Reproduction:**

---
**Mockups, screenshots, evidence:**

---

(Check one)
- [ ] Issue
- [x] Suggestion

**Comment by TobiTenno** [comment]
Needs to:
- [ ] Delete channel settings
- [ ] Delete guild settings
- [ ] Delete permissions
- [ ] Delete custom commands
- [ ] Delete stored settings for private channels
- [ ] Delete channels
- [ ] Delete tracked types for all channels
- [ ] Delete tracked items for all types

**Comment by TobiTenno** [comment]
Added with #166
