### ISSUE TITLE
LFG Suggestion "/lfg"

### ISSUE THREAD

**Issue by AcesGamingUK** [WFCD/genesis#160]
### Genesis Issue
---

**Summary (short):**

---
**Description:**
/lfg 'mission' 'runs' 'farming for' 'platform'
eg:
/lfg Hydron Endless AxiA3 XB1
---
**If issue, Reproduction:**

---
**Mockups, screenshots, evidence:**

![image](https://user-images.githubusercontent.com/16180389/34953028-9cbb3aa8-fa13-11e7-9d06-44a1b4c7ec6f.png)

![image](https://user-images.githubusercontent.com/16180389/34953902-43e11c4c-fa16-11e7-8a70-04399433306f.png)

---

(Check one)
- [ ] Issue
- [x] Suggestion

**Comment by AcesGamingUK** [comment]
so far I have this, but as I only started doing discord. js 12 hours ago it still needs work,
I'm planning on hopefully having the bot react on command,
and also figuring out how to have it only work when 4 params are used,
maybe even have the first param = a location.

`let Discord = module.require("discord.js")
  module.exports.run = async (bot, message, args) => {

  let LFG = new Discord.RichEmbed()
      .setAuthor(message.author.username)
      .setThumbnail("https://n8k6e2y6.ssl.hwcdn.net/images/warframeLogo.png")
      .setDescription("Looking For Group")
      .setColor("#ff00ff")
      .addField("Where?", `${args[0]}`, "true")
      .addField("How long?", `${args[1]}` , "true")
      .addField("Players Needed", `${args[2]}`, "true")
      .setFooter("Posted At")
      .setTimestamp(message.createdTimetamp);

  message.channel.send({embed: LFG});


}

module.exports.help = {
  name: "LFG"
}`

**Comment by TobiTenno** [comment]
oh, i can handle those parts... i'm more concerned/interested in what you want it to look like, the command itself

**Comment by AcesGamingUK** [comment]
however you feel is the easiest way to handle it. your the expert here compared to me XD

**Comment by AcesGamingUK** [comment]
slight update, thoughts? no idea if its a mess or not as im like noob 101
still cant figure out how to have "location" be a valid location,
`const Discord = module.require("discord.js");
//const list = (`../db.txt`)
    module.exports.run = async (bot, message, args) => {
      let msg = (args[0], args[1], args[2]);
      let location = args [0];
      let duration = args[1];
      let players = number(args[2]);

        let Nope = new Discord.RichEmbed()
          .setAuthor("Looking For Group Command Help")
          .setThumbnail(`${message.guild.iconURL}`)
          .setDescription("**__Usage__**: \n/LFG < location > < duration/wave amount > < players needed > \n eg: /LFG Hydron Endless 3")
          .setColor("#ff00ff")
          .addField("__Location:__", "Should Be A Playable Location")
          .addField("__Duration/Wave Amount:__", "For Survival/Defence** \nShould Be Endless, 5, 10, 15, 20 Etc \nif Not Then Should Be \"Grind\"")
          .addField("__Players Needed:__", "**For Non Raid** \nShould Be 1, 2, 3 \n**For Raid** \nShould Be 1, 2, 3, 4, 5, 6, 7,8")
          .setFooter("Posted At")
          .setTimestamp(message.createdTimetamp);

      if(!msg) return message.react('❌'),message.channel.send({embed: Nope});
      if(!location) return message.react('❌'),message.channel.send({embed: Nope});
      if(!duration) return message.react('❌'),message.channel.send({embed: Nope});
      if(isNaN(players)) return message.channel.send({embed: Nope});

      let LFG = new Discord.RichEmbed()
          .setAuthor(message.author.username)
          .setThumbnail("https://n8k6e2y6.ssl.hwcdn.net/images/warframeLogo.png")
          .setDescription("Looking For Group")
          .setColor("#ff00ff")
          .addField("Where?", `${args[0]}`, "true")
          .addField("waves?", `${args[1]}`, "true")
          .addField("Players Needed", `${args[2]}`, "true")
          .setFooter("Posted At")
          .setTimestamp(message.createdTimetamp);

          message.channel.send({embed: LFG});
          message.react('✅');
          message.delete([5000]);

  };
    module.exports.help = {
      name: "LFG"
  }
`

**Comment by TobiTenno** [comment]
what would you want the actual command to look like? `lfg hydron, sedna | 20m | 3`?

**Comment by AcesGamingUK** [comment]
yeah, that looks simple enough, maybe a note to say what you're grinding for?
`lfg [node] | [duration] | [players] | <reason>` [ ] = requried, < > = optinal 
`lfg Hydron | 30w | 3 | XP farming`

**Comment by TobiTenno** [comment]
Could do... whenever I start this, i'll reference back here... sorry i've had such a large backlog.

**Comment by AcesGamingUK** [comment]
no worries, totally understand, XD

**Comment by TobiTenno** [comment]
TODO:
- [ ] LFG Channel setting
- [ ] Show LFG channel setting in `/settings` command
- [ ] Structure for LFG command
- [ ] Webhook or just embed?

**Comment by TobiTenno** [comment]
finished up in dev, available on a branch, will deploy once the rest of the features are done.
