### ISSUE TITLE
price check

### ISSUE THREAD

**Issue by darkninjacl** [WFCD/genesis#163]
### Genesis Issue
price check 

**Summary (short):**

suck on processing search and wont pull up the prices
**Description:**

suck on processing search and wont pull up the prices
**If issue, Reproduction:**

---
**Mockups, screenshots, evidence:**

![screenshot 2](https://user-images.githubusercontent.com/35639460/35187661-da34a842-fdec-11e7-81ea-5fad36a0884c.png)

(Check one)
- [x] Issue
- [ ] Suggestion

**Comment by TobiTenno** [comment]
As I've explained several times, this is not on our end. we can't do anything about not getting a return on an async call until the receiver processes it and returns.
