### ISSUE TITLE
Sortie posting multiple times

### ISSUE THREAD

**Issue by pascaldulieu** [WFCD/genesis#167]
### Genesis Issue
Set sortie to track and its now posting 4 times
---
**Summary (short):**
Set the bot to un-track and then track sorties and now its posting over and over

---
**Description:**
Bot will post the same sortie event multiple times, currently doing it 4 times. I've come across this issue when the bot disconnects and reconnects and ends up having multiple sessions up at once causing it to post more than the set amount.

---
**If issue, Reproduction:**
Not sure how i would reproduce this issue.

---
**Mockups, screenshots, evidence:**
![image](https://user-images.githubusercontent.com/2935785/35484880-c1dcefd0-044e-11e8-9463-fb6d04fb6a74.png)
![image](https://user-images.githubusercontent.com/2935785/35484882-c84b9c18-044e-11e8-8b9f-2be7a84e8631.png)

---

(Check one)
- [x] Issue
- [ ] Suggestion

**Comment by TobiTenno** [comment]
yes, we're well aware. It's already tracked in #known-issues on the discussion and help server for genesis.
