### ISSUE TITLE
Assembly code pushes out update notes

### ISSUE THREAD

**Issue by LegacyValken** [WFCD/genesis#175]
### Genesis Issue
---

**Summary (short):**

Putting in assembly code causes the bot to spit out Update 8 patch notes.

---
**Description:**

If the person in a discord channel posts the following code, then the bot will post two to three seperate links regarding closed beta updates.

```
 mov DWORD PTR [rbp-4], edi
 mov DWORD PTR [rbp-8], esi
 cmp DWORD PTR [rbp-4], 1
```

---
**If issue, Reproduction:**

Can be produced.

---
**Mockups, screenshots, evidence:**

https://i.gyazo.com/2f76056760dd6e5a0f3472929ef8f08f.png

---

(Check one)
- [X] Issue
- [ ] Suggestion

**Comment by TobiTenno** [comment]
Do you have inline commands enabled? [] Are the wrappers for an info search.

**Comment by TobiTenno** [comment]
@LegacyValken can you check now? it should be fixed
