### ISSUE TITLE
hug.js

### ISSUE THREAD

**Issue by LwkasCrystian** [WFCD/genesis#196]
'use strict';

const Command = require('../../models/Command.js');

/**
 * Hug Genesis
 */
class Hug extends Command {
  /**
   * Constructs a callable command
   * @param {Bot} bot The bot object
   */
  constructor(bot) {
    super(bot, 'silly.hug', 'hug', 'Hug Genesis');
  }

  run(message) {
    this.messageManager.reply(message, '```haskell\nOperator, Cephalons do not g-g-g-give huuuu~~ Screw it. ⊂（♡⌂♡）⊃```', false, false);
    return this.messageManager.statuses.SUCCESS;
  }
}

module.exports = Hug;

**Comment by TobiTenno** [comment]
This doesn't seem to be an actual issue, closing.
