### ISSUE TITLE
Bounties are incorrect for nintendo switch

### ISSUE THREAD

**Issue by Kirihan** [WFCD/genesis#245]
### Genesis Issue
---
the relics shown for the bounties for nintendo switch on discord (ostron syndicate) mismatches what we have in-game

**Summary (short):**

---
Example, in the 40-60 bounty, genesis says is the Axi S4 as reward, but we got Axi C3 in-game

**Description:**

---

**If issue, Reproduction:**

---
**Mockups, screenshots, evidence:**
here a picture of the bounties in switch vs what genesis says
![picture](https://user-images.githubusercontent.com/45792238/49805578-709fbe80-fd23-11e8-80c0-d9bbfeaf21d8.jpg)

Genesis config:
![image](https://user-images.githubusercontent.com/45792238/49805638-97f68b80-fd23-11e8-963a-18c74c93ed96.png)

---

(Check one)
- [X] Issue
- [ ] Suggestion

**Comment by Kirihan** [comment]
I will do screenshots tomorrow, busy for the rest of the day

**Comment by TobiTenno** [comment]
@Kirihan hi, still waiting on screenshots.

**Comment by TobiTenno** [comment]
DE shows their drop tables only for PC, which the reward information is based on, I have no intention of changing that. If it was the names, I'd fix those, but switch being behind PC isn't something i can fix.
