### ISSUE TITLE
#Request Item specific tracking

### ISSUE THREAD

**Issue by fogx** [WFCD/genesis#247]
Is it possible to further specify tracked events, such as excluding individual items in the "weapons" category? So that frequently reoccuring events can be ignored? (Or is there already a feature to filter such things in discord/genesis?)

**Comment by TobiTenno** [comment]
no. this has been brought up several times in the support server, and due to them not being static, (ie, not being a set list that can easily be checked), or follow an exact pattern, there's no way we could accurately filter that way.
