### ISSUE TITLE
Doesn't respond to @ with nickname.

### ISSUE THREAD

**Issue by Fidgetcetera** [WFCD/genesis#249]
### Genesis Issue
---

**Summary (short):**  Setting a nickname breaks @'ing Genesis to input commands.

---
**Description:** When you set a nickname for Genesis and try to use commands with it, it does not respond.  Related to #73, perhaps a discord API update broke the fix or something. 

---
**If issue, Reproduction:**
1. set bot nickname.
2. try to do @ [nickname] to mention the bot and give it a command
---
**Mockups, screenshots, evidence:**
![image](https://user-images.githubusercontent.com/15249812/51794962-05169100-21ab-11e9-9c61-dd6738500442.png)
(cephalon steve was the goofy nickname we set genesis to. this happens with single-word nicknames too though.)
---

(Check one)
- [x] Issue
- [ ] Suggestion

**Comment by TobiTenno** [comment]
yeah, always wondered if it would happen, but it's not really designed for that to be the primary access. i'm changing it so it works soon, it'll come out with the i18n changes

**Comment by TobiTenno** [comment]
fixed in #250, it's deployed out to most clusters. If you find issues still or you're on shards 1-10, you've got the old version that i haven't deployed over yet.

**Comment by Fidgetcetera** [comment]
Confirmed to be working on my server, am I good to close this?

**Comment by TobiTenno** [comment]
go for it!
