### ISSUE TITLE
Genesis LFG Bug - Task crashes when removing reactions

### ISSUE THREAD

**Issue by Daarknes** [WFCD/genesis#272]
### Genesis LFG Bug - Task crashes when removing reactions
---

**Summary (short):**
When a user removes his 🔰-reaction (same for ❌), the bot-task for that LFG-request seems to crash, the bot is not responding to the message afterwards.

---
**Description:**
see 'Reproduction' below.
After what i understand of the code (i don't really know JS), the feature to remove a user from the lfg-request should be implemented in LFG/LFG.js, but it seems to have a bug somewhere.

---
**Reproduction:**
1) create a LFG-request via /lfg place | time | ...
2) another user clicks the 🔰-reaction to join (this step works as intended)
3) the other user removes his 🔰-reaction, but nothing happens

after step 3) the task for the LFG-task seems to have "crashed", since all other features don't work anymore, e.g. the original author can't use the ❌-reaction to cancel the request and the (automatic) expiration doesn't work either.

---
**Mockups, screenshots, evidence:**
After adding the :beginner: reaction (everything is fine atm):
![image](https://user-images.githubusercontent.com/8361636/62401587-23a77b80-b584-11e9-8683-568959093312.png)

After removing the :beginner: reaction (this task is broken now, the embed didn't update):
![image](https://user-images.githubusercontent.com/8361636/62401599-2c984d00-b584-11e9-8de8-e11b24d0e084.png)

You can't manually expire the request via :x:-reaction.
The 3 minutes for auto-expiration have also passed several minutes ago.
![image](https://user-images.githubusercontent.com/8361636/62401601-31f59780-b584-11e9-9215-55a2cbe81a91.png)

---

(Check one)
- [X] Issue
- [ ] Suggestion

**Comment by TobiTenno** [comment]
do you have logs of it crashing, or is it just speculation?

**Comment by TobiTenno** [comment]
the reason it didn't expire is that your "some time" was invalid....

**Comment by TobiTenno** [comment]
also, are you the one who posted the message, or did someone else? because... you can't delete someone elses

**Comment by Daarknes** [comment]
First of all, I didn't expect such a fast answer, thanks for that 😄.

> do you have logs of it crashing, or is it just speculation?

Since i'm not hosting the bot, i don't think i have access to the logs. I invited the bot from here:
https://discordbots.org/bot/genesis.
Is this hosted by yourself or some third party?
Is it possible that the bot above just runs older code?


>the reason it didn't expire is that your "some time" was invalid....

I can't find this reply here, but i got it as an email, so i'll answer that as well:
In my understanding 'time' and 'expiration time' are 2 different things. I set the 'expiration time' to 3min, which can be seen in the footer of the embed.


> also, are you the one who posted the message, or did someone else? because... you can't delete someone elses

In the third screenshot, i'm in fact the one who posted the message (i used 2 Discord-Accounts to test), so i should be able to manually expire.

**Comment by TobiTenno** [comment]
I tested this right after you reported it and it was working fine... The word of "task crashes" made it sound like you could see it crash as you used it, sorry for my confusion. 

If you can repro again consistently, let me know the shard you're on (displayed in the `/ping` command as shard XX of YY)

**Comment by Daarknes** [comment]
> If you can repro again consistently, let me know the shard you're on (displayed in the `/ping` command as shard XX of YY)

I have two different guilds where this problem happens (one is my own for testing, the other one for a gaming-clan). According to /ping,
one is on shard **8** of 30 and the other one shard **12** of 30

**Comment by TobiTenno** [comment]
okiedoke. at some point, if you can contact me on discord so i can try to hop on when you're testing it and i can watch the logs for errors, that'd be 👌

**Comment by Daarknes** [comment]
I sent you a friend request. Otherwise you can also just go directly to the server:
https://discord.gg/yYcRxbf

**Comment by TobiTenno** [comment]
I think we got it hammered out... right [here](https://github.com/WFCD/genesis/blob/master/src/commands/LFG/LFG.js#L136) `emooji` should be `emoji`. It'll be coming soon in a fix.

**Comment by TobiTenno** [comment]
got it fixed in what's deployed now. enjoy!
