### ISSUE TITLE
Your guild ETR is over the bot-to-user ratio.

### ISSUE THREAD

**Issue by syd-h** [WFCD/genesis#287]
Last Wednesday the 23rd I suddenly got a PM from the bot with this message with it leaving my server.

> Your guild ETR is over the bot-to-user ratio.
> Genesis will now leave.
> If you want to keep using Genesis please invite more people or kick some bots.

Is this something that you have implemented or something on Discord's side? I've tried asking their support and checking out their API documentation. They seriously have no search function... And I don't think I saw any updated from your side about new ratio limits?

**Comment by TobiTenno** [comment]
This is purely on our side and it's been at 80% for a long while.

**Comment by syd-h** [comment]
Will do. I had just shortened the server name since it's not the same as git name.

**Comment by TobiTenno** [comment]
All good. Hit me up anytime if you have more problems.
