### ISSUE TITLE
Idea: Seperate LFG based on flags

### ISSUE THREAD

**Issue by Greggaz** [WFCD/genesis#298]
**Summary:**
A suggestion for genesis would be to expand the flag system to the LFG module allowing custom game images to be added to the LFG such as the Warframe logo & Destiny 2 logo.

---
**If issue, Reproduction:**

---
**Mockups, screenshots, evidence:**

**Comment by TobiTenno** [comment]
what flags are you suggesting?

they're already separated by platforms that can be custom added per-instance, so you can do a `destiny:pc` and a `warframe:pc` separately... also, the logo on the embeds is our org logo, and that's not something i'm really planning on changing bot-wide...

**Comment by Greggaz** [comment]
Hey,

Yeah so basically I was wanting to see if it's possible if someone wants to create a Warframe LFG post then when they generate the post a Warframe image appears on the LFG post and if a destiny LFG post is created then the destiny logo appears. :) 

If this is not on the roadmap then that's fine just a suggestion :)

**Comment by TobiTenno** [comment]
hmmm, my worry is that it's trying to make LFG something it's not... since it's entirely user-decided, the ideal usage is that LFG's for a server would be either single-game or the user would specify, and people looking to join them would join in if they're looking...
