### ISSUE TITLE
SetPing not working for some invations

### ISSUE THREAD

**Issue by Delfic** [WFCD/genesis#498]
**Summary:**
We have a discord server where we use Genesis. We've set the ping for catalyst and reactor. We have genesis on a bot specific channel pumping out invasions and when those rewards show up we want it to notify the role.

For some cases it doesn't notify.

---
**If issue, Reproduction:**

On PC, when invasion is Exilus Adapter bp vs Orokin Reactor bp it doesn't ping the `reactor` reward.

---
**Mockups, screenshots, evidence:**
Didn't work for Exilus Adapter bp vs Orokin Reactor bp
![image](https://user-images.githubusercontent.com/4091284/129488538-fe99dba3-9b89-4078-8427-dfd74266e665.png)

Working when it's both reactor and catalyst, you can notice the two pings (correctly)
![image](https://user-images.githubusercontent.com/4091284/129488516-5c33bfa1-b9b9-444f-b20d-fd242ce378cc.png)

**Comment by TobiTenno** [comment]
I think I've abut got a fix, sorry for the massive wait, i had to wrap my mind around some of the ones not working
