### ISSUE TITLE
What should be in the file called genesis.json?

### ISSUE THREAD

**Issue by Usure-one** [WFCD/genesis#508]
**Summary:**
What should be in the file called genesis.json that is needed to start?
---
![2278ae524ce13ff2f18e7b4ff1eeecb5](https://user-images.githubusercontent.com/88494432/141646215-ed8fb54a-47b4-415a-8435-5a66c9a521c5.png)

**Comment by Usure-one** [comment]
Ah Nevermind i just found

**Comment by TobiTenno** [comment]
okiedoke. for future lookers, we detail this in the readme for whats from the pm2 environment configs
