### ISSUE TITLE
Add unified values

### ISSUE THREAD

**Issue by EliSauder** [WFCD/genesis#98]
When using the track/set ping commands currently you have to add everything by hand ex: 
```
/track fissures.t1 /track syndicate.meridian
/track fissures.t2 /track syndicate.arbiters
/track fissures.t3 /track syndicate.suda
/track fissures.t4 /track syndicate.loka            ...etc
```
it gets the job done, but it could be made for streamlined if you could make is so you just have to do, ex:
```
/track fissures /track syndicate
```
Doing this would make it so instead of typing everything out you just have to type the master value and then use the sub values to enable/disable individual ones. ex:
```
/track syndicate
/untrack syndicate.meridian
```
This enables tracking of all syndicates then disables tracking of steel meridian using only 2 commands instead of 5. Another one that may be nice is that when you do '/track resources' it would track all the possible resource alerts making it one command instead of 28.

This is just an idea that I came up with mainly when working with the '/set ping <thing to ping> <ping>' and thought that it would be nice to have some preset categories all ready to go instead of having to go through each and every individual one.

**Comment by aliasfalse** [comment]
I'll look into it. It currently operates this way for `events` and `items` with the track command. I don't like doing this too expansively because it adds far too much complexity to detail in documentation and make it easy for people to use.

**Comment by aliasfalse** [comment]
Progress:

[x] Track
[x] Untrack
[ ] Set Ping
