### ISSUE TITLE
Upgrade to /raid command

### ISSUE THREAD

**Issue by KawaZ19** [WFCD/genesis#99]
An upgrade for the `/raid` command, to allow to see the last 5 records of each raid.

Exemple:
`/raid [user] jordas` 
`/raid [user] retribution`
`/raid [user] retribution-nm`

or to see the X last records
`/raid [user] jordas [X]` 

`/raid [user] jordas 5` for the last 5 
`/raid [user] jordas 10` for the last 10
etc.

**Comment by aliasfalse** [comment]
i'd probably do the predictable stuff  before the user, but i'll look into it soon.

**Comment by aliasfalse** [comment]
while i like the idea, i don't know that it's practical, i guess.... what would this help with, @KawaZ19?

**Comment by aliasfalse** [comment]
still no answer from @KawaZ19... closing.
